bootstrapServers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
schemaRegistryUrl: http://schema-registry.private.prod.vivareal.io
groupId: dumping-machine
topics:
- name: prod-listings-listingsv3-avro-hybrid-v1
  bucketName: grupozap-datalake-dev
  bucketRegion: us-east-1
  partitionForget: 60000
